pipeline work

diff --git a/.github/workflows/cd.yaml b/.github/workflows/cd.yaml
--- a/.github/workflows/cd.yaml
+++ b/.github/workflows/cd.yaml
@@ -75,8 +75,42 @@ jobs:
 
       - name: send deploy command through SSM 
         run: |
-          aws ssm send-command \
-            --document-name "AWS-RunShellScript" \
-            --targets "Key=tag:Role,Values=seal-host" \
-            --parameters 'commands=["pwd","docker --version"]'
 
+          INSTANCE_ID=$( #save the instance id 
+            aws ec2 describe-instances \
+              --query 'Reservations[*].Instances[*].InstanceId' \
+              --filters \
+                "Name=tag:Role,Values=seal-host" \
+                "Name=instance-state-name,Values=running" \
+              --output text
+            )
+          
+          COMMAND_ID=$( #save the command id
+            aws ssm send-command \
+              --document-name "AWS-RunShellScript" \
+              --instance-ids "$INSTANCE_ID" \
+              --parameters 'commands=["pwd","docker --version"]' \
+              --query 'Command.CommandId' \
+              --output text
+            )
+
+          echo "Target instance: $INSTANCE_ID"
+          echo "SSM command: $COMMAND_ID"
+
+          set +e #for now, dont exit if we get error 
+          #wait until command is executed 
+          aws ssm wait command-executed \ 
+            --command-id "$COMMAND_ID" \
+            --instance-id "$INSTANCE_ID"
+          #if it fails save it here 
+          WAIT_EXIT_CODE=$? 
+
+          set -e #now we can exit on error 
+           #so even if the comamnd isnt executed because of error, we are still able to query it for info, otherwise it would just fail
+          aws ssm get-command-invocation \
+            --command-id "$COMMAND_ID" \
+            --instance-id "$INSTANCE_ID" \
+            --query '{Status:Status,ExitCode:ResponseCode,Stdout:StandardOutputContent,Stderr:StandardErrorContent}' \
+            --output json
+
+          exit "$WAIT_EXIT_CODE" #then we exit if command didnt execute 
